### ISSUE TITLE
Assertion `i0 < i1' failed.

### ISSUE THREAD

**Issue by inkdot7** [hanstt/plutt#7]
With config:
```
hist("XX", Pi1t)
hist("XX2", Pi1e)
```
the command:
```
./plutt -f r10.conf -r h509 r10_470-529_beam_proton_hit_track.root
```
Fails:
```
Built with: SDL2,freetype2,nlopt,ROOT,ucesb.
r10.conf: Parsing...
r10.conf: Done!
Signal=Pi1e
Signal=Pi1t
Pi1e. id=0 type=2
Pi1t. id=1 type=2
Starting input loop.
Starting event loop.
Exited input loop.51 (120k/s)
Exited event loop.
Entering main loop...
plutt: implutt.cpp:2088: void ImPlutt::Window::PlotHist1(const ImPlutt::Plot*, double, double, const std::vector<T>&, size_t) [with T = unsigned int; size_t = long unsigned int]: Assertion `i0 < i1' failed.
```
.root file from:
http://fy.chalmers.se/subatom/advsubdet/r10_470-529_beam_proton_hit_track.root

**Comment by hanstt** [comment]
Also fixed with [ef3b72c](https://github.com/hanstt/plutt/commit/ef3b72cb5e5bb62fb2a5a071e3b5099634173640).

**Comment by inkdot7** [comment]
I am on commit ef3b72c , still fails for me.  Note, different signal, `Pi1e`.

**Comment by inkdot7** [comment]
-inf could also come from analysis, e.g. if a time measurement is outside range.  I think I never did that so far, but does not feel very far-fetched.

**Comment by hanstt** [comment]
[9117479](https://github.com/hanstt/plutt/commit/9117479786ac09ee1c7708d8929b959dd46fe244) can deal with:
`hist("XX", Pi1t)
hist("XX2", Pi2t)

hist("XX3", Pi1t)
hist("XX4", Pi1e)

hist("YY", Tot)`
But does cheat by ignoring inf's... Will take care of them later, nan's too.
